name: medrefer_ai
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:       # CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
  # CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^3.1.3              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1
  supabase_flutter: ^2.0.0  # Added for Supabase integration
  flutter_dotenv: ^6.0.0    # Added for environment variable management
  provider: ^6.1.1          # Added for state management

  # Feature dependencies - safe to modify
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^1.1.0
  flutter_slidable: ^4.0.1
  google_maps_flutter: ^2.12.3
  camera: ^0.11.2
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  record: ^6.0.0
  file_picker: ^10.3.3
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  mobile_scanner: ^7.0.0-beta.8
  sqflite: ^2.3.0
  uuid: ^4.2.1
  intl: ^0.20.2
  flutter_stripe: ^12.0.2
  local_auth: ^2.1.6
  flutter_secure_storage: ^10.0.0-beta.4
  crypto: ^3.0.3
  encrypt: ^5.0.3
  email_validator: ^2.1.17
  flutter_webrtc: ^1.2.0
  http: ^1.1.0
  web_socket_channel: ^3.0.3
  flutter_barcode_scanner: ^2.0.0
  just_audio: ^0.9.36
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  xml: ^6.4.2                    # For XML processing and SOAP integrations
  csv: ^6.0.0                    # For CSV data processing
  pdf: ^3.10.7                   # For PDF report generation
  excel: ^4.0.6                  # For Excel report generation
  archive: ^3.4.10               # For file compression and archiving
  mime: ^1.0.4                   # For MIME type detection
  cron: ^0.6.0                   # For cron-based scheduling
  queue: ^3.1.0+2                # For task queue management
  retry: ^3.1.2                  # For retry mechanisms
  synchronized: ^3.1.0+1         # For thread synchronization
  collection: ^1.18.0            # For advanced collection operations
  meta: ^1.12.0                  # For metadata annotations

dev_dependencies:
  flutter_test:    # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^6.0.0 # CRITICAL: Required for code quality - DO NOT REMOVE
  sqflite_common_ffi: ^2.3.0  # Required for database testing
  mockito: ^5.4.4
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true # CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
  # CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # CRITICAL FONTS RULE: 
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES
